### ISSUE TITLE
Tutotial

### ISSUE THREAD

**Issue by alain93** [shakso/WorldWindow#1]
Hello,
 Great project but a tutorial/parts would be nice, thanks.

**Comment by shakso** [comment]
Parts are available in the Fritzing file/directory. 

To create a tutorial would require lots of steps/documentation - if you are confident with Linux, you should be able to work out what needs to be installed to get this working - none of the scripts are particularly complicated and are all under 200 lines.

**Comment by shakso** [comment]
If you have any questions, I'm happy to answer as well :)

**Comment by alain93** [comment]
ok thanks

**Comment by frelev** [comment]
I get "no sketch found in file" when trying to open the .fzz. Any special version needed of Fritzing?

**Comment by shakso** [comment]
It opens for me in Fritzing 0.9.9 (only downloaded AppImage a few weeks ago so it's probably the latest version)

**Comment by kwalkerk** [comment]
This is a terrific project.  You wouldn't happen to know if it will run using an Amazon Fire 4k TV stick?

**Comment by shakso** [comment]
You should be able to run the .apk on a Fire Stick, although I've never done this myself as all my devices are Android/Chromecast.

**Comment by kwalkerk** [comment]
Great - thanks.  I’ll get started on building this after the new year.

**Comment by toilamanimani** [comment]
I have the same problem as frelev when opening the .fzz.-file with Fritzing 0.9.9 (latest Version): 
"no sketch found in file"

Shakso, could you perhaps reupload the file/make minor changes to the file and reupload it?

Thank you so much! Great work!

**Comment by shakso** [comment]
I've re-uploaded the Fritzing file - had to re-create it a bit because the original didn't work for me, only had an incomplete backup. All the paths/connections/components should be there though.
