### ISSUE TITLE
hardware and software for track the person  

### ISSUE THREAD

**Issue by ilRisaIt** [shakso/WorldWindow#2]
Congratulations, a really nice project. Could you tell me the hardware and software you used to track the subject in front of the window? I'm looking in the various directories and I can't find it. Thank you

**Comment by shakso** [comment]
Thanks for the compliment.

The software for the person tracking can be found at https://github.com/shakso/WorldWindow/tree/main/arduino/ThermalControl - the hardware module used was an Adafruit MLX90640, coupled with an ESP32
